### ISSUE TITLE
stream_data not working

### ISSUE THREAD

**Issue by colaya19** [yhilpisch/tpqoa#10]
Error: 
Traceback (most recent call last):
  File "FXTutorial.py", line 72, in <module>
    mt.stream_data('EUR_USD', stop=100)
  File "/home/colaya/miniconda3/lib/python3.8/site-packages/tpqoa/tpqoa.py", line 286, in stream_data
    float(msg.bids[0].dict()['price']),
TypeError: 'NoneType' object is not subscriptable

How to produce it: 
mt = MomentumTrader('oanda.cfg', momentum=5) 
mt.stream_data('EUR_USD', stop=100)

**Comment by yhilpisch** [comment]
Streaming does not work on the weekend.

What is the content of the file `FXTutorial.py` that you are referencing?

**Comment by colaya19** [comment]
It's the python file that contains the lines of code that I posted above in the "How to produce it:" section. 

the definition for stream_data is as follows and I believe this could be part of the issue: 

![image](https://user-images.githubusercontent.com/25777836/117658383-a6516780-b168-11eb-9a5e-2f7f19d27573.png)

**Comment by colaya19** [comment]
I tried changing the parameter list from "stop=None" to just "stop" and it produced a separate error with line 286 about how msg.bids[0] is not iterable and when I change the line to "msg.bids.dict()['price']), " I get an error that theres no dict() for bids...

I call the method the same as how the READ.me has it, so I'm unsure why it's causing issues.
![image](https://user-images.githubusercontent.com/25777836/117659060-79ea1b00-b169-11eb-82f2-49b668cdbcdc.png)


If you want more screenshots let me know I'll grab them later.

**Comment by yhilpisch** [comment]
Did you properly set up the config file with appropriate credentials?

I can't reproduce the issue. For me it works as expected (just now as you see):

![Screenshot 2021-05-10 at 17 15 41](https://user-images.githubusercontent.com/4572544/117682455-5cda3a00-b1b3-11eb-985f-a35e597e206e.png)

**Comment by colaya19** [comment]
I believe so...the get_history fn seems to be working properly: 

code: 
![image](https://user-images.githubusercontent.com/25777836/117719878-f30a6200-b1ab-11eb-99cc-888228cc86bb.png)

output:
![image](https://user-images.githubusercontent.com/25777836/117719925-01f11480-b1ac-11eb-8cb4-a9ce129b0fdc.png)

**Comment by colaya19** [comment]
![image](https://user-images.githubusercontent.com/25777836/117725554-49c76a00-b1b3-11eb-90c6-a32bf7ae214d.png)

**Comment by yhilpisch** [comment]
The account ID does not seem to be a proper one (it is NOT your login name).

You find it in your account on oanda.com under "Manage Funds".

The exact format is like the following:

<img width="1215" alt="Screenshot 2021-05-11 at 10 39 51" src="https://user-images.githubusercontent.com/4572544/117785821-395fcf80-b245-11eb-973c-9d2bafd896ae.png">

**Comment by colaya19** [comment]
Wow lol! Thank you so much!
