### ISSUE TITLE
oanda.get_instruments() error #3

### ISSUE THREAD

**Issue by KalinStoyanov** [yhilpisch/tpqoa#11]
The same problem as #2. Please help

It is Anaconda, JupytrerLab 3.0.14, Python 3.7. The same problem on Jupyter Notebook and Spyder
Installed correct credentials with no quotes.
**content of pyalgo.cft**
[oanda]
account_id = KalinStoyanov2
access_token = 8279127d8a1c...
account_type = practice
**Resinstalled the token.**
Installed Desktop FXPractice

The working folder is archived on MS OneDrive. Available on this device

Here is my dialog.

[1] import tpqoa
[2] api = tpqoa.tpqoa('pyalgo.cfg')
[3] api.get_instruments()[:15]

ResponseNoField                           Traceback (most recent call last)
<ipython-input-3-3ba6b212a429> in <module>
----> 1 api.get_instruments()[:15]

~\anaconda31\lib\site-packages\tpqoa\tpqoa.py in get_instruments(self)
     85         ''' Retrieves and returns all instruments for the given account. '''
     86         resp = self.ctx.account.instruments(self.account_id)
---> 87         instruments = resp.get('instruments')
     88         instruments = [ins.dict() for ins in instruments]
     89         instruments = [(ins['displayName'], ins['name'])

~\anaconda31\lib\site-packages\v20\response.py in get(self, field, status)
     33 
     34         if value is None:
---> 35             raise ResponseNoField(self, field)
     36 
     37         return value
ResponseNoField: 400 response for GET https://api-fxpractice.oanda.com:443/v3/accounts/KalinStoyanov2/instruments does not have field 'instruments' (contains 'errorMessage')

**Comment by yhilpisch** [comment]
The account ID does not seem to be a proper one (it is NOT your login name).

You find it in your account on oanda.com under "Manage Funds".

The exact format is like the following:

![image](https://user-images.githubusercontent.com/4572544/118389229-2d02ba80-b629-11eb-8891-bb1364c0901d.png)

**Comment by KalinStoyanov** [comment]
It works now. Thank you
