### ISSUE TITLE
Granularity for four hours and below

### ISSUE THREAD

**Issue by theAfricanQuant** [yhilpisch/tpqoa#12]
![image](https://user-images.githubusercontent.com/33702921/124889550-e0f84480-dfdf-11eb-86f4-15ef1ec4ac83.png)
I have coded and indicator in Python to print out charts for me and a portion of my function call is shown on the image above for the weekly chart. It works also for the Daily charts and Monthly.

However when I try to load any time frame below the daily (eg four hours, 1 hour etc) I get the following error
![image](https://user-images.githubusercontent.com/33702921/124889993-44827200-dfe0-11eb-82e7-e02afe243b42.png)

what is the Granularity input for the 4 hours? is it H4? that doesn't work.

Thanks for the assist

**Comment by yhilpisch** [comment]
The API might not provide any granularity. Only default ones. H1 should work. You would need to resample probably to H4.

**Comment by theAfricanQuant** [comment]
"H1" has not worked but I discovered that "M30" does...so I will do the resample with that one instead. Thanks

**Comment by att90** [comment]
> The API might not provide any granularity. Only default ones. H1 should work. You would need to resample probably to H4.

Hello i had same issue. For second and minutes start and end time is calculated and running in loop. Adding H as well resolved my issue. Looks like it is out of range. Try small time window it should work without editing.

Changed line in tpqoa.py: 
from:
if granularity.startswith('S') or granularity.startswith('M'):
to:
if granularity.startswith('S') or granularity.startswith('M') or granularity.startswith('H'):

> "H1" has not worked but I discovered that "M30" does...so I will do the resample with that one instead. Thanks
