### ISSUE TITLE
Adding H to granularity

### ISSUE THREAD

**Issue by att90** [yhilpisch/tpqoa#13]
Hello Yves,

First of all thank you for the wrapper as i am new in python it helped my lot. 

I had an issue to get H4 history candles. After trying to understand the issue. I found if the granuality doesnt start with S or M it will add start and end at he default request without spliting the time to chunks, so it will possibly larger then 5000 candles. Maybe it will help someone else new to programing to not strugle to long why it doesnt work with H* cansles  :-)
Would be great to have it build in. Thank you

        if granularity.startswith('S') or granularity.startswith('M'):
            multiplier = float("".join(filter(str.isdigit, granularity)))
            if granularity.startswith('S'):
                # freq = '1h'
                freq = f"{int(MAX_REQUEST_COUNT * multiplier / float(3600))}H"
            else:
                # freq = 'D'
                freq = f"{int(MAX_REQUEST_COUNT * multiplier / float(1440))}D"
            data = pd.DataFrame()
            dr = pd.date_range(start, end, freq=freq)

            for t in range(len(dr)):
                batch_start = self.transform_datetime(dr[t])
                if t != len(dr) - 1:
                    batch_end = self.transform_datetime(dr[t + 1])
                else:
                    batch_end = self.transform_datetime(end)

                batch = self.retrieve_data(instrument, batch_start, batch_end,
                                           granularity, price)
                data = data.append(batch)
        else:
            start = self.transform_datetime(start)
            end = self.transform_datetime(end)
            data = self.retrieve_data(instrument, start, end,
                                      granularity, price)

**Comment by yhilpisch** [comment]
Added and pushed.
