### ISSUE TITLE
oanda connection error - KeyError: 'oanda'

### ISSUE THREAD

**Issue by feliperpo** [yhilpisch/tpqoa#14]
Hi - following instruction however not getting a connection. Please advise.

Steps:

1)pip install --upgrade git+https://github.com/yhilpisch/tpqoa.git
2)import tpqoa
3)api = tpqoa.tpqoa("Desktop/oanda.cfg")

(Using Atom to edit cfg file / Anaconda with Jupiter Lab 1.1.4)

error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-73-1ccd7f1d176a> in <module>
----> 1 api = tpqoa.tpqoa("Desktop/oanda.cfg")

~/opt/anaconda3/lib/python3.7/site-packages/tpqoa/tpqoa.py in __init__(self, conf_file)
    111         self.config = configparser.ConfigParser()
    112         self.config.read(conf_file)
--> 113         self.access_token = self.config['oanda']['access_token']
    114         self.account_id = self.config['oanda']['account_id']
    115         self.account_type = self.config['oanda']['account_type']

~/opt/anaconda3/lib/python3.7/configparser.py in __getitem__(self, key)
    956     def __getitem__(self, key):
    957         if key != self.default_section and not self.has_section(key):
--> 958             raise KeyError(key)
    959         return self._proxies[key]
    960 

KeyError: 'oanda'

--
TX

**Comment by yhilpisch** [comment]
Is the config file in the location you specify?

Can you post the contents of the config file?

Many users do not generate the config file correctly.

This is the format:

```
[oanda]
account_id = XYZ-ABC-...
access_token = ZYXCAB...
account_type = practice (default) or live
```

**Comment by feliperpo** [comment]
Yes - I saved it on my desktop. Also tpqoa folder. I've tried diff places. 

Content:

[oanda]
account_id = 101-001-20ACCNTID4-001
access_token = d910047625d86c8349ef3PRACTICEACCTOK-31e7cbf29e67e7d9d462b87ecac427f7
account_type = practice

**Comment by KeatonSaunders** [comment]
I am having the same problem - config file set up the same as above. Would appreciate the help. Thanks.

**Comment by yhilpisch** [comment]
Without the real values, I can't check.

I would assume that `tpqoa` does not find the file.

That you have maybe misspecified the path to the config file.

Just put it in the current working directory and only use the file name (and no path).

**Comment by feliperpo** [comment]
ok, I will try again. 

Real values:

[oanda]
account_id = 101-001-20263364-001
access_token = d910047625d86c8349ef36cbde96dd20-31e7cbf29e67e7d9d462b87ecac427f7
account_type = practice

**Comment by feliperpo** [comment]
Done! I'm in. Thanks
