### ISSUE TITLE
Connection to v20 REST server failed

### ISSUE THREAD

**Issue by BernardRenaud** [yhilpisch/tpqoa#16]
Back to the connection problem, some exception could be handled in **stream_data** function like the one below.
Indeed, a loop could be added in stream_data like:

```
        while(True):
            try: 
                   ..... streaming ....
            except ChunkedEncodingError:
                   ..... continue streaming ....
            except:
                raise
```

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/v20/response.py", line 52, in parts
    for line in self.lines:
  File "/root/miniconda3/lib/python3.9/site-packages/requests/models.py", line 797, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/root/miniconda3/lib/python3.9/site-packages/requests/models.py", line 756, in generate
    raise ChunkedEncodingError(e)
**requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/notebook/LiveTradingBots.py", line 483, in <module>
    bot.stream_data(depl_env.symbol, stop=stop)
  **File "/root/miniconda3/lib/python3.9/site-packages/tpqoa/tpqoa.py", line 346, in stream_data
    for msg_type, msg in response.parts():**
  File "/root/miniconda3/lib/python3.9/site-packages/v20/response.py", line 57, in parts
    raise V20ConnectionError(self.path)
v20.errors.V20ConnectionError: Connection to v20 REST server at XXXXXXXX=True failed

**Comment by BernardRenaud** [comment]
> Back to the connection problem, some exception could be handled in **stream_data** function like the one below:
> 
> Traceback (most recent call last):
> File "/root/miniconda3/lib/python3.9/site-packages/v20/response.py", line 52, in parts
> for line in self.lines:
> File "/root/miniconda3/lib/python3.9/site-packages/requests/models.py", line 797, in iter_lines
> for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
> File "/root/miniconda3/lib/python3.9/site-packages/requests/models.py", line 756, in generate
> raise ChunkedEncodingError(e)
> **requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/root/notebook/LiveTradingBots.py", line 483, in
> bot.stream_data(depl_env.symbol, stop=stop)
> **File "/root/miniconda3/lib/python3.9/site-packages/tpqoa/tpqoa.py", line 346, in stream_data for msg_type, msg in response.parts():**
> File "/root/miniconda3/lib/python3.9/site-packages/v20/response.py", line 57, in parts
> raise V20ConnectionError(self.path)
> v20.errors.V20ConnectionError: Connection to v20 REST server at XXXXXXXX=True failed

**Comment by Nohealz** [comment]
Did you find a fix to this? I get a ton of these errors.

FYI I am using the stream fail safe method currently but it would be nice if there was an actual fix.

**Comment by yhilpisch** [comment]
To be honest, we are currently not working on the wrapper. I don't know if and when an update for this would be included.
