### ISSUE TITLE
json ValueError

### ISSUE THREAD

**Issue by aistalker** [yhilpisch/tpqoa#17]
Not sure if this is the correct place for the issue but any help is appreciated.

This just popped up starting this morning. I cannot get the program to run.

`Traceback (most recent call last):
File "C:\Users\elect\anaconda3\lib\site-packages\tpqoa\tpqoa.py", line 373, in _stream_data_failsafe_thread
self.stream_data(args[0], callback=args[1])`

`File "C:\Users\elect\anaconda3\lib\site-packages\tpqoa\tpqoa.py", line 346, in stream_data
for msg_type, msg in response.parts():`

`File "C:\Users\elect\anaconda3\lib\site-packages\v20\response.py", line 53, in parts
yield parser(line)`

`File "C:\Users\elect\anaconda3\lib\site-packages\v20\pricing.py", line 783, in __call__
j = json.loads(line.decode('utf-8'))`
`ValueError: Expected object or value`

**Comment by yhilpisch** [comment]
This looks like a connection error.

But without a complete, minimal, verifiable code example that reproduces the error it is impossible to help.
