### ISSUE TITLE
error with example of getting EUR/USD history

### ISSUE THREAD

**Issue by fboerman** [yhilpisch/tpqoa#18]
Hi,

I am trying out this package. to start I tried to get the history of the EUR/USD pair
my code is as follows:
```python
import tpqoa
oanda = tpqoa.tpqoa('oanda.cfg')
print(oanda.get_instruments())
data=oanda.get_history(instrument='EUR_USD',start='2021-10-01', end='2021-10-30', granularity='1h', price='A')
```
The print call is executed just fin and the EUR/USD pair is listed in there.
but the error I get from the package is:
```
v20.errors.ResponseNoField: 400 response for GET <url> does not have field 'candles' (contains 'errorMessage')
```
when use the url returned by the package and put it in curl to see what the error message is it returns this:
```
{
  "errorMessage": "Insufficient authorization to perform request."
}
```

what is going on here? can someone help me here? Thanks in advance!

**Comment by yhilpisch** [comment]
Did you sign up for a demo account with Oanda? Did you configure the credentials file correctly?

**Comment by fboerman** [comment]
Hi,

Yes I did. It connects fine and I get get for example a list of instruments.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by point049** [comment]
I am getting the same error
@yhilpisch any idea what I might need to try?

**Comment by yhilpisch** [comment]
The line to retrieve the data contains an error (must read "H1"):

```
data = oanda.get_history(instrument='EUR_USD', start='2021-10-01', 
         end='2021-10-30', granularity='H1', price='A')
```

This works fine for me.

**Comment by point049** [comment]
Strangely it fails on my side with the same parameters:

instrument = 'EUR_USD'  
start = '2021-10-01'  
end = '2021-10-30'  
granularity = 'H1'  
price = 'A'

api = tpqoa.tpqoa('pyalgo.cfg')
data = api.get_history(instrument, start, end, granularity, price) # api 

Output error:
ResponseNoField: 401 response for GET [https://api-fxpractice.oanda.com:443/v3/instruments/EUR_USD/candles?price=A&granularity=H1&from=2021-10-01T00%3A00%3A00.000000000Z&to=2021-10-04T00%3A00%3A00.000000000Z](https://api-fxpractice.oanda.com/v3/instruments/EUR_USD/candles?price=A&granularity=H1&from=2021-10-01T00%3A00%3A00.000000000Z&to=2021-10-04T00%3A00%3A00.000000000Z) does not have field 'candles' (contains 'errorMessage')

**Comment by yhilpisch** [comment]
Your credentials file is probably not correct. Check the exact syntax as explained/shown for tpqoa in the README.

**Comment by point049** [comment]
Thanks very much Yves for your swift feedback. Indeed I had unnecessarily added '' to the value of the key, and account id.
