### ISSUE TITLE
Pandas Version

### ISSUE THREAD

**Issue by bkearns16** [yhilpisch/tpqoa#20]
What version of pandas is used when calling get_history()? It appears to be outdated and how can it be updated? It will not allow the pandas function date_range() to be used.

**Comment by yhilpisch** [comment]
I used `tpqoa` today and it worked as desired.

Can you please post a reproducible example with your traceback and pandas version used:

How to create a Minimal, Complete, and Verifiable example
https://stackoverflow.com/help/mcve

**Comment by bkearns16** [comment]
In [1]: import tpqoa

In [2]: api = tpqoa.tpqoa("/home/brad/config/pyalgo.cfg")

In [3]: instrument = "EUR_USD"
   ...: start = "2019-01-17"
   ...: end = "2022-01-19"
   ...: granularity = "H1"
   ...: price = "B"

In [4]: data = api.get_history(instrument, start, end, granularity, price)

In [5]: data.date_range(start="2019-01-17 00:00:00", end="2020-01-17 00:00:00")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [5], in <module>
----> 1 data.date_range(start="2019-01-17 00:00:00", end="2020-01-17 00:00:00")

File ~/.local/lib/python3.8/site-packages/pandas/core/generic.py:5478, in NDFrame.__getattr__(self, name)
   5471 if (
   5472     name not in self._internal_names_set
   5473     and name not in self._metadata
   5474     and name not in self._accessors
   5475     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5476 ):
   5477     return self[name]
-> 5478 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'date_range'

**Comment by yhilpisch** [comment]
I do not know where you have this particular line of code from. But this works:

```python
In [1]: import tpqoa
   ...: 
   ...: api = tpqoa.tpqoa("data/pyalgo.cfg")
   ...: 
   ...: instrument = "EUR_USD"
   ...: start = "2019-01-17"
   ...: end = "2022-01-19"
   ...: granularity = "H1"
   ...: price = "B"

In [2]: data = api.get_history(instrument, start, end, granularity, price)

In [3]: data.loc["2019-01-17 00:00:00":"2020-01-17 00:00:00"]
Out[3]: 
                           o        h        l        c  volume  complete
time                                                                     
2019-01-17 00:00:00  1.13985  1.13987  1.13940  1.13976     372      True
2019-01-17 01:00:00  1.13975  1.14002  1.13935  1.13935     506      True
2019-01-17 02:00:00  1.13937  1.13958  1.13878  1.13895     483      True
2019-01-17 03:00:00  1.13899  1.13905  1.13855  1.13878     288      True
2019-01-17 04:00:00  1.13881  1.13891  1.13817  1.13821     426      True
...                      ...      ...      ...      ...     ...       ...
2020-01-16 20:00:00  1.11345  1.11376  1.11339  1.11374     914      True
2020-01-16 21:00:00  1.11372  1.11377  1.11338  1.11341     499      True
2020-01-16 22:00:00  1.11349  1.11360  1.11304  1.11358     137      True
2020-01-16 23:00:00  1.11360  1.11369  1.11350  1.11364     241      True
2020-01-17 00:00:00  1.11363  1.11387  1.11345  1.11370     618      True

[6215 rows x 6 columns]

In [4]: 
```

**Comment by bkearns16** [comment]
The date_range function raises an error which I believe is due to the pandas in the tpqoa module being old: 

https://stackoverflow.com/questions/28228090/module-object-has-no-attribute-date-range-in-python

**Comment by yhilpisch** [comment]
You are mixing things up here.

`tpqoa` uses whatever `pandas` version is on your machine.

`pd.date_range()` is used to create `DatetimeIndex` objects with `pandas`.

The `DataFrame` object does NOT have a `.date_range()` method as in your code.

You need to simply use the `.loc[]` indexer as in my code.

**Comment by bkearns16** [comment]
Thanks for the clarification and your time.
