### ISSUE TITLE
Deprecation warning : method 'append'

### ISSUE THREAD

**Issue by urielblanco** [yhilpisch/tpqoa#21]
https://github.com/yhilpisch/tpqoa/blob/aba477202328a35dcb255710c000f4bb86755513/tpqoa/tpqoa.py#L234

Hi, in my jupyter nb a warning message started to appear: the frame.append method will be deprecated exactly, you can see in the line above.

When you call the method e.g: get_history in granularity of S5 the message appears several times and is annoying.
I can solve this problem changing the the 'append' for this:

`                data = pd.concat([data, batch])
`

https://pandas.pydata.org/docs/dev/whatsnew/v1.4.0.html#deprecations

**Comment by yhilpisch** [comment]
Updated and pushed.
