### ISSUE TITLE
Is it possible to set the take profit as a distance instead of price?

### ISSUE THREAD

**Issue by point049** [yhilpisch/tpqoa#22]
I see the stop loss and trailing stop can be specified in terms of distance, which is great and practical as we don't know in advance what the fill price would be for a market order.

Is it possible to also specify the take profit as a distance?

create_order():
             sl_distance: float
                 stop loss distance price, mandatory eg in Germany
             tsl_distance: float
                 trailing stop loss distance
             tp_price: float
                 take profit price to be used for the trade

**Comment by yhilpisch** [comment]
The Oanda API does not support this for the Take Profit order.

One would need to write some logic that translates the distance into price.
