### ISSUE TITLE
warning when calling api.get_history

### ISSUE THREAD

**Issue by facohen** [yhilpisch/tpqoa#23]
Please note that when calling api.get_history with pandas==1.5.1 I get the following warning

/opt/conda/envs/python_forex/lib/python3.10/site-packages/tpqoa/tpqoa.py:161: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(batch)

**Comment by yhilpisch** [comment]
Indeed, this needs to be updated to use `pd.concat()`.
