### ISSUE TITLE
Why is stream_data freezing after getting just the first tick on Oanda?

### ISSUE THREAD

**Issue by dpark15** [yhilpisch/tpqoa#24]
Hi,

I've been using tpqoa to build an automated trading bot for Oanda. But stream_data freezes after just fetching one tick. Below is a screenshot from my Jupyter Notebook that shows how my AWS server froze for over an hour after fetching just one tick. Why is this happening? And how can I fix it? Thanks!

<img width="480" alt="image" src="https://user-images.githubusercontent.com/16129010/219884556-4783631e-4ecd-4ccd-8378-62916732d8a1.png">

David

**Comment by yhilpisch** [comment]
There is no tick (streaming) data on weekends.

Trading stops in the evening European time.

It resumes on Monday morning European time.
