### ISSUE TITLE
get_transactions() only pulls up to 'id': '1000'

### ISSUE THREAD

**Issue by Nohealz** [yhilpisch/tpqoa#25]
If I have a LOT of transactions, the base function without passing any args only returns transaction 'id' 1-1000.

**My account example**
get_transactions(13000) returns 'id' 13001 - 14000

Going through the v20 documentation I cannot figure out how to request only the latest transactions. (I'm no expert though)

It's also very time consuming to always pull in blocks of 1000. I really just want to pull the last 50 or so. Any help greatly appreciated.

**Comment by yhilpisch** [comment]
When you place an order, you need to capture the order ID.

With that ID, you can retrieve the most recent transactions only.

Say `ID=14512`, then you can use e.g. `api.get_transactions(ID - 8)`.

**Comment by Nohealz** [comment]
Appreciate the info. I wanted to automate finding the latest transactions because I don't always have the last order info handy. Here's a little bruteforce way to get there if anyone needs.

I'm getting very frequent server connection errors, hence the try/except.

```
x = 0
while True:
    try:
        transactions = oanda.get_transactions(x)
    except Exception as e:
        print("error occurred at x = {}, trying again".format(x))
        print(e)
        continue
    else:
        if len(transactions) == 1000:
            print("Tried 'get_transactions({}), but still not at the end of the account".format(x))
            x += 1000
            continue
        else:
            print("Reached the end of the account, saving latest 'id'")
            break
```
