### ISSUE TITLE
create_order return variable with SL 

### ISSUE THREAD

**Issue by michalisfrangos** [yhilpisch/tpqoa#27]
The returned variable from create_order() doesn't return any information regarding the SL order, as we see in the example in the notebook of this REPO

It would be helpful to know if the SL order was opened, and its id.  Any chance to return this order info as well please?

**Comment by yhilpisch** [comment]
When you get the return object for the base order with the transaction id, the SL order usually has transaction id+1. You can retrieve the SL order information by using `api.get_transaction()`.

```
order = api.create_order('EUR_USD', units=10000, sl_distance=0.01, ret=True)

 {'id': '3550', 'time': '2023-06-27T06:12:25.191543220Z', 'userID': 13834683,  ...} 

api.get_transaction(tid=int(order['id']) + 1)

{'id': '3551',
 'time': '2023-06-27T06:12:25.191543220Z',
 'userID': 13834683,
 'accountID': '101-004-13834683-001',
 'batchID': '3549',
 'requestID': '25093739189409910',
 'type': 'STOP_LOSS_ORDER',
 'tradeID': '3550',
 'price': 1.08242,
 'distance': '0.01',
 'timeInForce': 'GTC',
 'triggerCondition': 'DEFAULT',
 'reason': 'ON_FILL'}
```

**Comment by michalisfrangos** [comment]
thanks,  this is a simple approach using existing functionality.
