### ISSUE TITLE
TypeError in tpqoa.py package in __init__(self, conf_file)

### ISSUE THREAD

**Issue by johangenis** [yhilpisch/tpqoa#6]
Hi,
I get the below error when attempting to establish a connection to my OANDA Practice account:

api = tpqoa.tpqoa("oanda.cfg")

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-d3e726e9e5ca> in <module>
----> 1 api = tpqoa.tpqoa("oanda.cfg")

~/Library/Python/3.8/lib/python/site-packages/tpqoa/tpqoa.py in __init__(self, conf_file)
     67             self.stream_hostname = 'stream-fxpractice.oanda.com'
     68 
---> 69         self.ctx = v20.Context(
     70             hostname=self.hostname,
     71             port=443,

TypeError: __init__() got an unexpected keyword argument 'token'

My oanda.cfg looks like this:

[oanda]
account_id = 101-004-8861064-001
access_token = ddab9dd1e464036643cb7a4574e83d87-a35a1948575e9825dacfaac49bb90b00
account_type = practice

My pip freeze:

appnope==0.1.2
APScheduler==3.6.3
as==0.1
asgiref==3.2.7
attrs==19.3.0
autopep8==1.5
backcall==0.2.0
black==19.10b0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
coreapi==2.3.3
coreschema==0.0.4
decorator==4.4.2
Django==3.0.5
django-extensions==2.2.8
django-rest-swagger==2.2.0
djangorestframework==3.11.0
entrypoints==0.3
flake8==3.7.9
flake8-black==0.1.1
Flask==1.1.1
idna==2.9
ipykernel==5.4.2
ipython==7.19.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
itypes==1.1.0
jedi==0.17.2
jupyter-client==6.1.7
jupyter-core==4.7.0
mccabe==0.6.1
numpy==1.19.4
openapi-codec==1.3.2
packaging==20.3
pandas==1.2.0
parso==0.7.1
pathspec==0.7.0
pd==0.0.1
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.8
ptyprocess==0.6.0
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.7.3
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.3.1
pyzmq==20.0.0
redis==3.4.1
regex==2020.1.8
requests==2.23.0
six==1.15.0
sqlparse==0.3.1
toml==0.10.0
tornado==6.1
tpqoa @ git+https://github.com/yhilpisch/tpqoa@025ee329f21089db44f1da49fb81cdf1e872422d
traitlets==5.0.5
typed-ast==1.4.1
tzlocal==2.0.0
ujson==4.0.1
uritemplate==3.0.1
urllib3==1.25.8
v20==3.0.25.0
wcwidth==0.2.5
Werkzeug==1.0.0

**Comment by yhilpisch** [comment]
I cannot replicate your error.

For me, the API object instantiation works as expected with both my config file and your credentials. 

With your credentials, I can't retrieve any data though while everything works fine with mine.

Are these your real credentials? If so, you should generate a new token.

**Comment by johangenis** [comment]
Hi Yves,

Thank you for your reply.  My oanda.cfg looks like this:

[oanda]
account_id = 101-004-8861064-001
access_token =
3405cd8a260cf728d6137537b114a013-faa5cfdf5e557ad1c25c32c197c2d990
account_type = practice

My OS is MacOS Big Sur and I am using Jupyter Notebooks.

I hope this helps to resolve this issue.

Kind Regards,

Johan

**Comment by yhilpisch** [comment]
Your credentials work fine for me out of the box.
I only needed to remove the line break before the access token. It must start one blank after the equal sign.
How exactly did you install the package? You should use in any case:

`pip install git+git://github.com/yhilpisch/tpqoa`

**Comment by czhang165** [comment]
Hi Johan and yhilpisch,

I met exactly the same error associated with the "token" argument. Was it caused some inconsistency in class instantiation?

**Comment by czhang165** [comment]
I attach my .cfg file for your info.

[oanda]
account_id = czhang611
access_token = 5311142f5f9a0953fcc887ecc950ffd8-9f2c49e5df7993c12cd7d848aa3388b2
account_type = practice

OS: Win10

Regards,

**Comment by yhilpisch** [comment]
You account ID in the config file seems to be wrong.

On Windows you should use the following install command:

`pip install git+https://github.com/yhilpisch/tpqoa.git`

**Comment by czhang165** [comment]
Thanks for your reply!
After re-install the package, the issue was solved.

**Comment by bendiaz** [comment]
I'm having the same issue as OP.

my config file looks like this:

[oanda]
account_id = 101-001-18083277-001
access_token = a4e104c4a297e33b0160866cacd781fc-8e2534fa57eacdba97341854e04f5a9a 
account_type = practice

OS: High Sierra 10.13.6

I installed using this command:
`pip install --index-url https://test.pypi.org/simple/ tpqoa`

**Comment by yhilpisch** [comment]
Use the installation command as follows:

`pip install git+https://github.com/yhilpisch/tpqoa.git`

The command you used is deprecated and not shown in the `README.md` anymore.
