### ISSUE TITLE
v20.errors.ResponseNoField: 400 response

### ISSUE THREAD

**Issue by marcelhfm** [yhilpisch/tpqoa#8]
While trying to create an order with a stop-loss-distance or a take-profit-price I get following error: "v20.errors.ResponseNoField: 400 response for POST".  With the error message: errorMessage	"Insufficient authorization to perform request.". 
Once I remove the stop loss distance and the take-profit-price no error is raised.

I've tried to find the 400 error Insufficient authorization on the developer OANDA documentation but I couldn't find it.
Is this some sort of syntax error on my part, or is this a known bug?

Example Code for clarification:

```
trader = tpqoa.tpqoa("cfgfile.cfg")

trader.create_order("EUR_USD", units=100000,  sl_distance=0.0002, tp_price=1.19200, suppress=True, ret=True)

# -> 400 Error: "Insufficient Authorization"
```

Once I leave out the sl_distance and the tp_price no error is raised.

Has anybody else run into this problem? 

Another question rather unrelated to this problem:
Is there any way to create/change  a stoploss order after units have been bought/sold? 
According to the V20 rest API this should be possible, but if I'm correct it hasn't been implemented in the wrapper.
Is that correct? If so one could implement it oneself, for example with the requests package?

**Comment by yhilpisch** [comment]
Did you try with other parameter values for `sl_distance` and `tp_price`? I would assume that one or two of the values might cause the 400 error. E.g. 0.0002 looks too small to be allowed. Must be 1 pip at lease.

Changes to orders are not directly possible via tpqoa, but via the v20 package.

**Comment by marcelhfm** [comment]
Thank you, this resolved the problem. sl_distance has to be minimum 1 pip.

**Comment by yhilpisch** [comment]
True 1 pip not 1% (which would not make sense given the leverage involved).
